name: '🚔'
on: [ push ]
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: go test -v -vet 'all' ./...
